### ISSUE TITLE
Сделать несколько разных точек "швартов"

### ISSUE THREAD

**Issue by mavka** [jolaf/rigging#1]
В режиме "где снасть?" https://rawgit.com/jolaf/rigging/master/shtandart.html#where , вопрос про швартов.

Швартовых много, в процессе тренировки по привычке выбираешь один, тот, про который точно знаешь. Имхо надо спрашивать точнее. Например, швартов на баке, полуюте, юте. Ну или если точки крепления стабильно являются носовым/кормовым шпринтом/продольным, то так эти точки и назвать, чтобы они были разными.

**Comment by jolaf** [comment]
Fixed at #2d94d69.
